force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>Position to be filled</description>
    <label>Position</label>
    <nameField>
        <displayFormat>POS - {00000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>select department</description>
    <inlineHelpText>.............................</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/positionExtension.cls
public class positionExtension{
    private Final Position__c position;
    Public string positionTypeId{get; set;}
    Public positionExtension(Apexpages.Standardcontroller positioncontroller){
        this.position = (Position__c)positioncontroller.getRecord();
    }
    public list<selectoption> positionTypeOption{
    get{
        List<selectOption> positionType = new List<selectOption>();
        for(Position__c ptr:[select name from Position__c pt where pt.Department__c = :position.Department__c order By name]){
            positionType.add(new selectoption(ptr.id,ptr.name));
        }
        return positionType;
    }
    private set;}
}