force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>Position to be filled</description>
    <label>Position</label>
    <nameField>
        <displayFormat>POS - {00000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Total_Close_Pos__c.field-meta.xml
<CustomField>
    <fullName>Total_Close_Pos__c</fullName>
    <label>Total Close Pos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Total_Open_Pos__c.field-meta.xml
<CustomField>
    <fullName>Total_Open_Pos__c</fullName>
    <label>Total Open Pos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PositionRecWithPollerExtension.cls
public class PositionRecWithPollerExtension{
    public list<Position__c> positionRecord{get;set;}
    public PositionRecWithPollerExtension(Apexpages.StandardSetController controller){
        positionRecord = [select id,name,Total_Open_Pos__c,Total_Close_Pos__c from Position__c];
    }
    public List<wrapper2> getOpenCloseCount(){
        list<wrapper2> ListWrapper = new list<wrapper2>();
        for(Position__c posObj:positionRecord){
            ListWrapper.add(new wrapper2(posObj.Name,posObj.Total_Open_Pos__c,posObj.Total_Close_Pos__c));
        }
        return ListWrapper;
    }
    public class wrapper2{
        public string PosName{get;set;}
        public Decimal OpenCount{get;set;}
        public Decimal CloseCount{get;set;}
        public Wrapper2(string myName,Decimal myOpenCount,Decimal myCloseCount){
            this.PosName = myName;
            this.OpenCount = myOpenCount;
            this.CloseCount = myCloseCount;
        }
    }
}

/*system.debug('----- positionRecord -----'+positionRecord);
system.debug('----- positionRecord -----'+positionRecord.size());
system.debug('----- ListWrapper -----'+ListWrapper);
system.debug('----- ListWrapper -----'+ListWrapper.size());*/