force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>this object hold job application details</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job_status__c.field-meta.xml
<CustomField>
    <fullName>Job_status__c</fullName>
    <label>Job status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>holds info about position</description>
    <inlineHelpText>......................................</inlineHelpText>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>Position to be filled</description>
    <label>Position</label>
    <nameField>
        <displayFormat>POS - {00000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Total_Close_Pos__c.field-meta.xml
<CustomField>
    <fullName>Total_Close_Pos__c</fullName>
    <label>Total Close Pos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Total_JA__c.field-meta.xml
<CustomField>
    <fullName>Total_JA__c</fullName>
    <description>total job application for position</description>
    <inlineHelpText>......................................................</inlineHelpText>
    <label>Total JA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Total_Open_Pos__c.field-meta.xml
<CustomField>
    <fullName>Total_Open_Pos__c</fullName>
    <label>Total Open Pos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MergePosJaBatchClass.cls
public class MergePosJaBatchClass implements Database.Batchable<Sobject>,database.stateful{
    
    public Map<id,decimal> pidvsTotalJobapp = new map<id,decimal>();
    public map<id,decimal> pidvsOpencount = new map<id,decimal>();
    public map<id,decimal> pidvsClosecount = new map<id,decimal>();
    
    public string soqlQuery = '';
    
    public MergePosJaBatchClass(string Query){
        system.debug('----- inside Query Cons -----');
        this.soqlQuery = Query; 
    }
    
    Public Database.QueryLocator start(Database.BatchableContext Bc){
        system.debug('===== in start soqlQuery ====='+soqlQuery);
        return Database.getQueryLocator(soqlQuery);
    }
    
    Public void execute(Database.BatchableContext bc,list<sObject> sobjlist){
        if(sobjlist.size() > 0){
            sObject sobj = sobjlist[0];
            system.debug('===== inside execute sobj [0] ====='+sobj);
            if(sobj.getSObjectType().getdescribe().getname() == 'Job_Application__c'){
                system.debug('===== in execute if =====');
                jobAppLogic(sobjlist);
            }
            else if(sobj.getSObjectType().getdescribe().getname() == 'Position__c'){
                system.debug('===== in execute else =====');
                positionLogic(sobjlist);
            }
        }
    }
    
    Public void finish(Database.BatchableContext bc){
        system.debug('---pidvsTotalJobapp---'+pidvsTotalJobapp);
        system.debug('---pidvsOpencount---'+pidvsOpencount);
        system.debug('---pidvsClosecount---'+pidvsClosecount);
            
        MAP<Id,Position__c> posMAP = new MAP<Id,Position__c>();
        for(Id posID : pidvsTotalJobapp.keySet()){
            fillPositionMAPforUpdate(posMAP,pidvsTotalJobapp, posID, pidvsTotalJobapp.get(posID), 'Total');
        }
        for(Id posID : pidvsOpencount.keySet()){
            fillPositionMAPforUpdate(posMAP,pidvsOpencount, posID, pidvsOpencount.get(posID), 'Open');
        }
        for(Id posID : pidvsClosecount.keySet()){
            fillPositionMAPforUpdate(posMAP,pidvsClosecount, posID, pidvsClosecount.get(posID), 'Close');
        }
        system.debug('---posMAP---'+posMAP);
        if(posMAP.size()>0){
            Database.executeBatch(new SobjectUpdateBatch(posMAP.values()), 1);
        }
    }
    
    public void positionLogic(list<Position__c> PosObjList){
        For(Position__c posobj1 : PosObjList){
            integer oflag=0,cflag =0;
            if(posobj1.Job_Applications__r != Null && posobj1.Job_Applications__r.size() > 0){
                
                callUpdateMapLogic(posobj1.Job_Applications__r,oflag,cflag);
            }else{
                pidvsTotalJobapp.put(posobj1.id,0);
                pidvsOpencount.put(posobj1.Id, 0); 
                pidvsClosecount.put(posobj1.Id, 0);
            } 
        }
    }
        
    public void jobAppLogic(list<Job_Application__c> jobObjList){
        integer oflag=0,cflag =0;
        callUpdateMapLogic(jobObjList,oflag,cflag);
    }
    
    //Private Methods For Computation of busines Logic
    public void fillPositionMAPforUpdate(MAP<Id,Position__c> posMAP, Map<id,decimal> valueMap, Id posID, Decimal val, String var){
        Position__c pos = new Position__c();
        pos.Id = posID;
        if(posMAP.containskey(posID)){
            pos = posMAP.get(posID);
        } 
        if(var == 'Open'){
            pos.Total_Open_Pos__c = valueMap.get(posID) != null ? valueMap.get(posID) : 0 ;  
        }else if(var == 'Close'){
            pos.Total_Close_Pos__c = valueMap.get(posID) != null ? valueMap.get(posID) : 0 ;  
        }else if(var == 'Total'){
            pos.Total_JA__c = valueMap.get(posID) != null ? valueMap.get(posID) : 0 ;  
        }
        posMAP.put(posID, pos);
    }
    
//integer openflag = 0; 
//integer closeflag = 0;
    private void callUpdateMapLogic(list<Job_Application__c> jobObjList,integer oflg,integer cflg){
        
        for(Job_Application__c jobj : jobObjList){
            updateCountMAP( pidvsTotalJobapp, jobj.Position__c);
            if(jobj.Job_status__c == 'Open') {
                oflg++;
                updateCountMAP( pidvsOpencount, jobj.Position__c);
            }
            else if (jobj.Job_status__c == 'close'){
                cflg ++;
                updateCountMAP( pidvsClosecount, jobj.Position__c);
            }
       }
        /*if (oflg == 0){
            updateCountMAP( pidvsOpencount, jobj.Position__c);
        }*/ 
       //if(openflag == 0) pidvsOpencount.put(key, value)
    }

    private void updateCountMAP( map<id,decimal> pidvscount, ID posID){
        //if(openflag == 0)  pidvsOpencount.put(posID, 0);
        //if(closeflag == 0) pidvsClosecount.put(posID, 0);
        if(pidvscount.containsKey(posID)) 
            pidvscount.put(posID, pidvscount.get(posID)+1);
        else pidvscount.put(posID, 1); 
    } 

}