force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>this object hold job application details</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/count_of_app__c.field-meta.xml
<CustomField>
    <fullName>count_of_app__c</fullName>
    <description>count of number</description>
    <inlineHelpText>-----------------------------</inlineHelpText>
    <label>count of app</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>holds info about position</description>
    <inlineHelpText>......................................</inlineHelpText>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>Position to be filled</description>
    <label>Position</label>
    <nameField>
        <displayFormat>POS - {00000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/sum_of_position__c.field-meta.xml
<CustomField>
    <fullName>sum_of_position__c</fullName>
    <description>sum of job app field count</description>
    <label>sum of position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/sumofcountBatchclass.cls
public class sumofcountBatchclass implements Database.Batchable<sobject>,Database.stateful {
    map<id,decimal> pidVscountja = new  map<id,decimal>();
    
    public Database.QueryLocator Start(Database.BatchableContext bc){
        return Database.getQueryLocator('select id,name,count_of_app__c,Position__c from Job_Application__c');
    }
    public void execute(Database.BatchableContext bc, List<Job_Application__c> jalist){
        //add value and position id to map
        for (Job_Application__c JAobj: jalist){
            if(JAobj.count_of_app__c != null)
            	callupdatepidVscountja(pidVscountja,JAobj.Position__c,JAobj.count_of_app__c);
        }
    }
    public void finish(Database.BatchableContext bc){
        system.debug(' ----- pidVscountja ----- '+pidVscountja);
        //create list of position id and value
        list<Position__c> posIdvaluelist = new list<Position__c>();
        for(id posid : pidVscountja.keySet()){
            fillposIdvaluelist(posid,pidVscountja.get(posid),posIdvaluelist);
        }
        system.debug(' ----- posIdvaluelist ----- '+posIdvaluelist);
        update posIdvaluelist;
    }
    
    // Private Methods For Computation
     private void callupdatepidVscountja(map<id,decimal> MapidvsValue ,id posid,decimal value){
        if(MapidvsValue.containskey(posid)){
        	decimal getcountfromMAp = MapidvsValue.get(posid);
        	MapidvsValue.put(posid, getcountfromMAp +  value);
        }
        else MapidvsValue.put(posid, value);
    }
    private void fillposIdvaluelist(id IdofPosition , decimal countvalue , list<Position__c> idvaluelist){
        Position__c posobj = new Position__c();
        posobj.Id = IdofPosition;
        posobj.sum_of_position__c = countvalue;
        idvaluelist.add(posobj);
    }

}




////if(pidVscountja.containsKey(JAobj.Position__c)){
//decimal getcountfromMAp = pidVscountja.get(JAobj.Position__c);
                    //pidVscountja.put(JAobj.Position__c, getcountfromMAp + JAobj.count_of_app__c );
                //}
                //else{
                    //pidVscountja.put(JAobj.Position__c, JAobj.count_of_app__c );
                //}
 /*Position__c posobj = new Position__c();
            posobj.Id = posid;
            posobj.sum_of_position__c = pidVscountja.get(posid);
            posIdvaluelist.add(posobj);*/