force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>this object hold job application details</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job_status__c.field-meta.xml
<CustomField>
    <fullName>Job_status__c</fullName>
    <label>Job status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>holds info about position</description>
    <inlineHelpText>......................................</inlineHelpText>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/location__c/location__c.object-meta.xml
<CustomObject>
    <description>This object holds information about office locations</description>
    <label>location</label>
    <nameField>
        <label>location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>Position to be filled</description>
    <label>Position</label>
    <nameField>
        <displayFormat>POS - {00000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>select department</description>
    <inlineHelpText>.............................</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Education_Requri__c.field-meta.xml
<CustomField>
    <fullName>Education_Requri__c</fullName>
    <description>Select requirement</description>
    <inlineHelpText>...............................</inlineHelpText>
    <label>Education Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High school</fullName>
            </value>
            <value>
                <fullName>College</fullName>
            </value>
            <value>
                <fullName>Masters</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>Post-doc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The hiring manager for the position</description>
    <label>Hiring Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <label>Job Description</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/location__c.field-meta.xml
<CustomField>
    <fullName>location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the location of the position</description>
    <label>location</label>
    <referenceTo>location__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Programming_Language__c.field-meta.xml
<CustomField>
    <fullName>Programming_Language__c</fullName>
    <description>select language</description>
    <inlineHelpText>............................</inlineHelpText>
    <label>Programming Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COBOL</fullName>
            </value>
            <value>
                <fullName>FORTRAN</fullName>
            </value>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Perl</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>select your status</description>
    <inlineHelpText>..................................</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Sub_status__c.field-meta.xml
<CustomField>
    <fullName>Sub_status__c</fullName>
    <description>select sub status</description>
    <inlineHelpText>..............................</inlineHelpText>
    <label>Sub-status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/positioncon.cls
public with sharing class positioncon {

    public PageReference Cancel() {
        return null;
    }


    public positioncon() {

    }

    
    public id positionID{get;set;}
    public Position__c pos{get;set;}
    public list<Jobappwrapper> jobWrapperList{get;set;}
    public string forpagesec1{get;set;}
    public boolean Rendervalue{get;set;}
    
    public positioncon(ApexPages.StandardController controller) {
        positionID = ApexPages.currentpage().getparameters().get('id');
        system.debug('----- positionID  -----'+positionID );
        forpagesec1 = 'cunstructor called';
        Rendervalue = false;
        
        list<Position__c> postitionList = [select id,name,Start_Date__c,location__c,Job_Description__c,Hiring_Manager__c,Department__c,Education_Requri__c,Status__c,Sub_status__c,Programming_Language__c from Position__c where id = :positionID ];
        if(postitionList != null && postitionList.size()>0){
        
            pos = postitionList.get(0);
            system.debug('----- pos.id -----'+pos.id);
            jobWrapperList = new list<Jobappwrapper>();
            
            list<Job_Application__c> listofJobAppliction = [select id,Name,Job_status__c,Position__c from Job_Application__c where  Position__c =: pos.id ];
            system.debug('-----listofJobAppliction -----'+listofJobAppliction );
            
            for(Job_Application__c  job : listofJobAppliction ){
                system.debug('===== job.id ====='+job.id);
                system.debug('===== job.Position__c ====='+job.Position__c);
                Jobappwrapper Obj = new Jobappwrapper();
                obj.isselected = false;
                obj.JobApplicationObject = job;
                jobWrapperList.add(Obj);
            }
            system.debug('-----jobWrapperList -----'+jobWrapperList.size() );
            
        }    
    }
    public void saverecord(){
        system.debug('-----jobWrapperList -----'+jobWrapperList );
        
        list<Job_Application__c> updateJObAppList = new list<Job_Application__c>();
        forpagesec1 = 'saverecord called';
        Rendervalue = true;
        
        for(Jobappwrapper UpdateJOb : jobWrapperList){
            
            system.debug('-----jobWrapperList isselected -----'+UpdateJOb.isselected);
            system.debug('-----jobWrapperList JobApplicationObject-----'+UpdateJOb.JobApplicationObject.Name);
            if(UpdateJOb.isselected){
                updateJObAppList.add(UpdateJOb.JobApplicationObject);
            }
        }
        update pos;
        update updateJObAppList;
    }
    public class Jobappwrapper
        {
            public boolean isselected{get;set;}
            public Job_Application__c JobApplicationObject{get;set;}
        }

   

}