force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>this object hold job application details</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>holds info about position</description>
    <inlineHelpText>......................................</inlineHelpText>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>Position to be filled</description>
    <label>Position</label>
    <nameField>
        <displayFormat>POS - {00000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Mytab.cls
public class Mytab {
    public id positionID{get;set;}
    public list<Job_Application__c> jobappName{get;set;}
    public Mytab(ApexPages.StandardController controller){
        positionID = ApexPages.currentpage().getparameters().get('id');
        system.debug('----- positionID -----'+positionID);
        jobappName = [select name from Job_Application__c where Position__c =: positionID];
        system.debug('----- jobappName -----'+jobappName);
         system.debug('----- jobappName -----'+jobappName.size());
    }
    public Component.Apex.tabpanel getmyTabsJOB(){
        system.debug('----- positionID -----'+positionID);
        component.Apex.TabPanel MyTabPanel = new component.Apex.TabPanel();
        for(Job_Application__c jobObj :jobappName ){
            component.Apex.Tab ChildTab = new component.Apex.Tab();
            ChildTab.label = 'Tab--' + string.valueOf(jobObj.Name);
            MyTabPanel.ChildComponents.add(ChildTab);
        }
        return MyTabPanel;
    }
    public Component.Apex.pageBlock getMysection(){
        component.Apex.pageBlock MyBlock = new component.Apex.pageBlock();
        for(Job_Application__c jobObj :jobappName){
            component.Apex.pageBlockSection Mysection = new component.Apex.pageBlockSection();
            Mysection.Title = jobObj.name;
            
            MyBlock.Childcomponents.add(Mysection);
        }
        return MyBlock;
    }
}