force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>this object hold job application details</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job_status__c.field-meta.xml
<CustomField>
    <fullName>Job_status__c</fullName>
    <label>Job status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>holds info about position</description>
    <inlineHelpText>......................................</inlineHelpText>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>Position to be filled</description>
    <label>Position</label>
    <nameField>
        <displayFormat>POS - {00000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Total_Close_Pos__c.field-meta.xml
<CustomField>
    <fullName>Total_Close_Pos__c</fullName>
    <label>Total Close Pos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Total_JA__c.field-meta.xml
<CustomField>
    <fullName>Total_JA__c</fullName>
    <description>total job application for position</description>
    <inlineHelpText>......................................................</inlineHelpText>
    <label>Total JA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Total_Open_Pos__c.field-meta.xml
<CustomField>
    <fullName>Total_Open_Pos__c</fullName>
    <label>Total Open Pos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/totalJaOnPositionBatchClass.cls
public class totalJaOnPositionBatchClass Implements Database.Batchable<sobject>,Database.stateful{
    public Map<id,decimal> pidvsTotalJobappNew = new map<id,decimal>();
    public map<id,decimal> pidvsOpencountNew = new map<id,decimal>();
    public map<id,decimal> pidvsClosecountNew = new map<id,decimal>();
    
    public Database.QueryLocator Start(Database.BatchableContext Bc){
        return Database.GetQueryLocator('Select id,name,Total_JA__c,Total_Close_Pos__c,Total_Open_Pos__c,(Select id,name,Job_status__c,Position__c from Job_Applications__r) from Position__c');
    }
    public void Execute(Database.BatchableContext bc,List<Position__c> poList){
        For(Position__c posobj1 : poList){
            
            if(posobj1.Job_Applications__r != Null && posobj1.Job_Applications__r.size() > 0){
                For(Job_Application__c job1 : posobj1.Job_Applications__r){
                    if(pidvsTotalJobappNew.containsKey(posobj1.id)){ 
                        decimal TotalJacount = pidvsTotalJobappNew.get(posobj1.id); 
                        pidvsTotalJobappNew.put(posobj1.id,TotalJacount+1);
                    }
                    else{
                        pidvsTotalJobappNew.put(posobj1.id,1);
                    }
                }
            }
            else{
                pidvsTotalJobappNew.put(posobj1.id,0);
            }
        }
        For(Position__c posobj : poList){
            if(posobj.Job_Applications__r != Null && posobj.Job_Applications__r.size() > 0){
            	
                integer oflag=0,cflag =0;
                
                For(Job_Application__c job : posobj.Job_Applications__r ){
                    
                    if(job.Job_status__c == 'Open'){
                        
                        oflag++;
                        
                        if(pidvsOpencountNew.containsKey(posobj.Id)){
                            decimal opencount = pidvsOpencountNew.get(job.Position__c); 
                            pidvsOpencountNew.put(posobj.Id, opencount+1);
                        }
                        else pidvsOpencountNew.put(posobj.Id, 1); 
                    }
                    else if(job.Job_status__c == 'Close'){
                       
                        cflag++;
                       
                        if(pidvsClosecountNew.containsKey(posobj.Id)){ 
                           decimal Closecount = pidvsClosecountNew.get(job.Position__c); 
                           pidvsClosecountNew.put(posobj.Id, Closecount+1);
                       }
                       else pidvsClosecountNew.put(posobj.Id, 1); 
                    }
                    
                    /*else{
                        system.debug('else inside after open close');
                        pidvsOpencountNew.put(posobj.Id, 0);
                        pidvsOpencountNew.put(posobj.Id, 0);
                    }*/
                    
                } 
                if(oflag == 0){
                    system.debug('inside open flag 0');
                    pidvsOpencountNew.put(posobj.Id, 0); 
               
                }
                if(cflag == 0){
                    system.debug('inside close flag 0');
                     pidvsClosecountNew.put(posobj.Id, 0);
                }
            }
            else { 
                pidvsOpencountNew.put(posobj.Id, 0); 
                pidvsClosecountNew.put(posobj.Id, 0); 
            }
        }
    }
    public void Finish(Database.BatchableContext bc){
        System.debug('===== Finish total job count map ====='+pidvsTotalJobappNew +'\n ===== Finish Open count map ====='+pidvsOpencountNew +'\n===== Finish Close count map ====='+pidvsClosecountNew );} 
}

/*system.debug('===== in execute List<Position__c> po ====='+po);
        system.debug('===== in execute List<Position__c> po size ====='+po.size());
 system.debug('===== in side for if not null job app list ====='+posobj1.Job_Applications__r);
                system.debug('===== in side for if not null job app list size ====='+posobj1.Job_Applications__r.size());
system.debug('===== in side for else null job app list ====='+posobj1.Job_Applications__r);
  System.debug('===== in side for else Total Ja count map ====='+pidvsTotalJobappNew);
 System.debug('===== Execute Total Ja count map ====='+pidvsTotalJobappNew);
        System.debug('===== Execute Open count map ====='+pidvsOpencountNew);
        System.debug('===== Execute Close count map ====='+pidvsClosecountNew);

*/