force-app/main/default/objects/Invoice_Statement__c/Invoice_Statement__c.object-meta.xml
<CustomObject>
    <description>WAREHOUSE Description Of Invoice Statement</description>
    <label>Invoice Statement</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Statement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Statement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Des of on Voice</description>
    <inlineHelpText>...........................</inlineHelpText>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>WAREHOUSE</description>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Invoice_Statement__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Statement__c</fullName>
    <description>Des of Invoice Statement</description>
    <inlineHelpText>..........................................</inlineHelpText>
    <label>Invoice Statement</label>
    <referenceTo>Invoice_Statement__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Merchandise__c.field-meta.xml
<CustomField>
    <fullName>Merchandise__c</fullName>
    <description>Des Of Line Item</description>
    <inlineHelpText>.............................</inlineHelpText>
    <label>Merchandise</label>
    <referenceTo>Merchandise__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Price of Each Item</description>
    <inlineHelpText>................................</inlineHelpText>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Units_Sold__c.field-meta.xml
<CustomField>
    <fullName>Units_Sold__c</fullName>
    <description>Des of Units Sold</description>
    <inlineHelpText>..............................</inlineHelpText>
    <label>Units Sold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/Merchandise__c.object-meta.xml
<CustomObject>
    <description>WAREHOUSE List Of Merchandise</description>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchandise__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Merchandise Description</description>
    <inlineHelpText>.........................................</inlineHelpText>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Enter Merchandise Price</description>
    <inlineHelpText>........................................</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/fields/Total_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Total_Inventory__c</fullName>
    <description>Total Price Of Merchandise</description>
    <inlineHelpText>.............................................</inlineHelpText>
    <label>Total Inventory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MerchandiseOperation.cls
public class MerchandiseOperation {
    public static Id invoice(string pname , integer psold , string pdesc ){
        Merchandise__c m = [select Price__c,Total_Inventory__c from Merchandise__c where name = :pname limit 1];
        system.assertNotEquals(null, m);
        system.debug('merchandise m -- '+m);
        Invoice_Statement__c in1 = new Invoice_Statement__c(Description__c = pdesc);
        system.debug('invoice statement -- '+in1);
        insert in1;
        Line_Item__c li1 = new Line_Item__c(Name = '1', Invoice_Statement__c = in1.id , Merchandise__c = m.id , Unit_Price__c = m.Price__c , Units_Sold__c = psold);
        system.debug('units sold -- '+li1.Units_Sold__c);
        system.debug('line item -- '+li1);
        
        system.debug('total inventory -- '+m.Total_Inventory__c);
        insert li1;
        m.Total_Inventory__c =psold - m.Total_Inventory__c ;
        update m;
        system.debug('total inventory -- '+m.Total_Inventory__c);
        return in1.id;
    }

}