force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>all details of candidate</description>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>shows candidate age</description>
    <inlineHelpText>.....................................</inlineHelpText>
    <label>Age</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <description>enter education.....</description>
    <inlineHelpText>..........................</inlineHelpText>
    <label>Education</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <description>shows candidate email id</description>
    <inlineHelpText>............................................</inlineHelpText>
    <label>Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>enter your first name</description>
    <label>First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Enter Your Last Name</description>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>this object hold job application details</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <description>Hold all information of candidate</description>
    <inlineHelpText>.....................................................</inlineHelpText>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Candidate_Qualified__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Qualified__c</fullName>
    <description>shows qualification yes Or no</description>
    <formula>IF
(
CASE(  Position__r.Education_Requri__c  ,
 
&quot;High School&quot;, 1,
&quot;College&quot;, 2, 
&quot;Masters&quot;, 3,
&quot;PhD&quot;, 4,
&quot;Post-doc&quot;, 5,0)


&gt;


CASE(  Candidate__r.Education__c  ,  
&quot;High School&quot;, 1,
&quot;College&quot;,2, 
&quot;Masters&quot;, 3,
&quot;PhD&quot;, 4,
&quot;Post-doc&quot;, 5, 0), 


&quot;Not Qualified&quot;, &quot;Qualified&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>..................................................</inlineHelpText>
    <label>Candidate Qualified</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/count_of_app__c.field-meta.xml
<CustomField>
    <fullName>count_of_app__c</fullName>
    <description>count of number</description>
    <inlineHelpText>-----------------------------</inlineHelpText>
    <label>count of app</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_status__c.field-meta.xml
<CustomField>
    <fullName>Job_status__c</fullName>
    <label>Job status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>holds info about position</description>
    <inlineHelpText>......................................</inlineHelpText>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>Position to be filled</description>
    <label>Position</label>
    <nameField>
        <displayFormat>POS - {00000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/JobApplictionCompCont.cls
public class JobApplictionCompCont {
    public id assignPositionID{get;set;}
    public string assignCandidateID{get;set;}
    public list<Job_Application__c> getJobApplicationRecord(){
        return [select id,name,Job_status__c,Candidate_Qualified__c,count_of_app__c,Candidate__r.id,Candidate__r.Name from Job_Application__c where Position__c =: assignPositionID];
    }
    public list<Candidate__c> getCandidateRecord(){
        return [select id,name,Age__c,Education__c,Email_Id__c,First_Name__c,Last_Name__c from Candidate__c where id =: assignCandidateID];
    } 
}