force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>all details of candidate</description>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>shows candidate age</description>
    <inlineHelpText>.....................................</inlineHelpText>
    <label>Age</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <description>enter education.....</description>
    <inlineHelpText>..........................</inlineHelpText>
    <label>Education</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <description>shows candidate email id</description>
    <inlineHelpText>............................................</inlineHelpText>
    <label>Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>enter your first name</description>
    <label>First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Enter Your Last Name</description>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>this object hold job application details</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <description>Hold all information of candidate</description>
    <inlineHelpText>.....................................................</inlineHelpText>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_status__c.field-meta.xml
<CustomField>
    <fullName>Job_status__c</fullName>
    <label>Job status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CandidateViewExtension.cls
public class CandidateViewExtension {
    public id CanID{get;set;}
    public Candidate__c candidateObj{get;set;}
    public list<candidateWrapper> candidateWrapperlist{get;set;}
    
    public CandidateViewExtension(ApexPages.StandardController controller) {
        candidateObj = (Candidate__c)controller.getrecord();
        system.debug('----- candidateObj -----'+candidateObj );
        system.debug('----- candidateObj  id -----'+candidateObj.id);
        list<Candidate__c> candidateList = [select id,name,Age__c,Education__c,Email_Id__c,First_Name__c,Last_Name__c from Candidate__c where id =:candidateObj.id ];
        if(candidateList != null && candidateList.size()>0){
            system.debug('----- candidateList size -----' +candidateList.size());
            candidateObj = candidateList.get(0);
            candidateWrapperlist = new list<candidateWrapper>();
            list<Job_Application__c> ListOfJobApp = [select id,name,Job_status__c from Job_Application__c where Candidate__c =: candidateObj.id ];
            for(Job_Application__c ObjJob : ListOfJobApp ){
                candidateWrapper ObjWrap = new candidateWrapper();
                
                ObjWrap.JobAppObj = ObjJob;
                candidateWrapperlist.add(ObjWrap);
            }
        }
    }
    public class candidateWrapper{
        public Job_Application__c JobAppObj{get;set;}
    }

}