force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>all details of candidate</description>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>shows candidate age</description>
    <inlineHelpText>.....................................</inlineHelpText>
    <label>Age</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <description>enter education.....</description>
    <inlineHelpText>..........................</inlineHelpText>
    <label>Education</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <description>shows candidate email id</description>
    <inlineHelpText>............................................</inlineHelpText>
    <label>Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>enter your first name</description>
    <label>First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Enter Your Last Name</description>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>this object hold job application details</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <description>Hold all information of candidate</description>
    <inlineHelpText>.....................................................</inlineHelpText>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_status__c.field-meta.xml
<CustomField>
    <fullName>Job_status__c</fullName>
    <label>Job status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CandidateExtension.cls
public class CandidateExtension {
    
    public id CandidateID{get;set;}
    public Candidate__c candidate{get;set;}
    public list<JobApplicationWrap> JobApplicationWrapList{get;set;}
    
    public CandidateExtension(ApexPages.StandardController controller) {
        CandidateID = ApexPages.CurrentPage().getparameters().get('id');
        system.debug('----- CandidateID -----'+CandidateID);
        
        
        list<Candidate__c> candidateList = [select id,name,Age__c,Email_Id__c,Education__c,First_Name__c,Last_Name__c from Candidate__c where id =:CandidateID];
        if(candidateList != null && candidateList.size()>0){
            candidate = candidateList.get(0);
            JobApplicationWrapList = new list<JobApplicationWrap>();
            
            list<Job_Application__c> jobAppList = [select id,Name,Job_status__c,Candidate__c from Job_Application__c where Candidate__c=:CandidateID ];
            system.debug('------ jobAppList ------'+jobAppList);
            for(Job_Application__c JOb: jobAppList){
                JobApplicationWrap Wrapper = new JobApplicationWrap();
                Wrapper.JobApp = JOb;
                Wrapper.checkBox = false;
                JobApplicationWrapList.add(Wrapper);
            }
        }
    }
    
    public void Updaterecord(){
        list<Job_Application__c> UpdateCandidateList = new List<Job_Application__c>();
        for(JobApplicationWrap WRAPObj: JobApplicationWrapList){
            if(WRAPObj.checkBox){
                UpdateCandidateList.add(WRAPObj.JobApp);
            }
        }
        update candidate;
        update UpdateCandidateList;
    }
    
    public class JobApplicationWrap{
        public boolean checkBox{get;set;}
        public Job_Application__c JobApp{get;set;}
    }
    
    @testVisible
    private List<String> getFieldsList(){
        
        List<String> fldList = new List<String>();
        fldList.add('Name');
        fldList.add('Age__c');
        fldList.add('Email_Id__c');
        fldList.add('Education__c');
        fldList.add('First_Name__c');
        fldList.add('Last_Name__c');
        
        return fldList;
    }
    
}